### ISSUE TITLE
How to active the theme?

### ISSUE THREAD

**Issue by tp** [andischerer/vscode-theme-atom-one-dark#1]
I could install the theme just fine using the command from the gallery, but it did not active automatically in VSCode 1.1.

Adding some info on how to active this to the README would be much appreciated.

**Comment by andischerer** [comment]
Type `Theme` in the command palette > `Preferences: Color Theme` > `Atom One Dark`
![installtheme](https://cloud.githubusercontent.com/assets/930604/15219139/e4d207d4-1862-11e6-80ef-cb690268c0a8.gif)
